### ISSUE TITLE
use dpdk send only

### ISSUE THREAD

**Issue by ktprime** [leoll2/UDPDK#3]
can I use your lib send udp packet only, and recv udp packet from epoll(linux kernel)?

**Comment by leoll2** [comment]
Hello! 
Yes, the packets generated by UDPDK are technically well-formed UDP ones, so you should be able to receive them on a different interface even if it's driven by the linux kernel.

**Comment by ktprime** [comment]
Thanks for your details explain, UDPDK is a good design and it's api easy to use.  I've plan to send quic(udp) packets by using dpdk to accelerate. 
(according my benchmark linux udp's api sendmmsg is quite slow than tcp), my program is single thread (multiple process) which runs on linux server. can your udpdk lib runs on multi process environment?

**Comment by leoll2** [comment]
While UDPDK itself is two-process framework, it's not possible yet to share the same poller (secondary process) across multiple primary processes. On the other hand, if your cores run independent applications, with a proper DPDK configuration you may be able to run multiple instances of UDPDK in parallel (provided you have enough hw resources).
