### ISSUE TITLE
 POLLINIT: Waiting to initialize IPC...

### ISSUE THREAD

**Issue by ph12073396** [leoll2/UDPDK#4]
Hello,
I started the pktgen with default command  ./pktgen -c ../../config.ini -f send -s 100 -r 10000 -l pktgen-send.log
It keeps saying 
 _**POLLINIT: Waiting to initialize IPC...**_

my config.ini as below
[dpdk]
cores_primary=2
lcores_secondary=4
n_mem_channels=2

[port0]
mac_addr=00:11:22:33:44:50
ip_addr=127.0.0.1

[port0_dst]
mac_addr=00:11:22:33:44:60

the 2 mac addr (50 and 60) are the VFs setup on my NIC.
I'm new to DPDK. Your comments are very welcome.

**Comment by ertza** [comment]
I am also encountering the same issue, although I am trying to run the pingpong application.

> ./pingpong -c ../../config.ini -f ping -d 10000 -l pingpong.log
Application args: ./pingpong -l 2 -n 2 --proc-type=primary -- -f ping -d 10000 -l pingpong.log
Poller args: ./pingpong -l 4 -n 2 --proc-type=secondary
EAL: Detected 128 lcore(s)
EAL: Detected 128 lcore(s)
EAL: Detected 4 NUMA nodes
EAL: Detected 4 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: No legacy callbacks, legacy socket not created
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket_1207442_4ea5ceb56512a
INIT: Port 0 is invalid (out of range or not attached)
INIT: Cannot initialize RX port 0
INTR: Killing the poller process (1207442)...
CLOSE: Killing the poller process (1207442)...
Caught signal 15 in pingpong main process
INTR: Killing the poller process (0)...
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...
EAL: No legacy callbacks, legacy socket not created
POLLINIT: Waiting to initialize IPC...
POLLINIT: Waiting to initialize IPC...
POLLINIT: Waiting to initialize IPC...
POLLINIT: Waiting to initialize IPC...
POLLINIT: Waiting to initialize IPC...

**Comment by dkuo123** [comment]
same "Waiting to initialize IPC.." when using igb_uio.ko driver in AWS EC2 box. is it supported?

**Comment by leoll2** [comment]
@ph12073396 

> [port0]
mac_addr=00:11:22:33:44:50
ip_addr=127.0.0.1

The IP looks wrong, you set it to localhost. You should select the IP of the interface you use with DPDK.

**Comment by leoll2** [comment]
@ertza 

> INIT: Port 0 is invalid (out of range or not attached)
INIT: Cannot initialize RX port 0

Is the DPDK port properly configured and working? How is your UDPDK config.ini?

**Comment by leoll2** [comment]
@dkuo123 

> same "Waiting to initialize IPC.." when using igb_uio.ko driver in AWS EC2 box. is it supported?

Not officially supported because I don't have HW to test it atm, but it should work if DPDK supports it for your hardware.
