### ISSUE TITLE
Target does not have the DPDK KNI Module & KNI: Can not open /dev/kni

### ISSUE THREAD

**Issue by ashish4u125** [leoll2/UDPDK#8]
I have installed UDPDK on my server machine which has enp5s0f0 and enp5s0f1 NIC card and  I followed all the steps as mentioned in the Readme.md file but when I was inserting KNI module while setting up linux environment by using **./dpdk-setup.sh**, it is giving me the error "**Target does not have the DPDK KNI Module. To fix, please try to rebuild target**". I did rebuilt the target but the error remains the same. Also while I was running the sample applications (**ip_pipeline**) under example folder of DPDK, I am stucking at  **KNI: Can not open /dev/kni** message.

### What I have done
1.) I read the DPDK Documentation from [https://doc.dpdk.org/guides/prog_guide/kernel_nic_interface.html](the following page) and in its 47.1 point it states that you need to load **rte_kni.ko** file which is not available in /kernel/linux/kni of DPDK (version 20.05).
2.) I enabled CONFIG_RTE_LIBRTE_KNI=y which is in UDPDK/deps/dpdk/config# nano common_base.

How to enable/import KNI module into DPDK. And how to get **rte_kni.ko** file  in /kernel/linux/kni.

**Comment by leoll2** [comment]
Hi Ashish, your error relates to DPDK (as opposed to UDPDK) so you may get more help by asking to the [DPDK](https://github.com/DPDK/dpdk) community.  
The documentation in your link refers to the latest version, that's why it may be inconsistent with the version you use; I recommend checking the [docs for 20.05](https://doc.dpdk.org/guides-20.05/).

**Comment by ashish4u125** [comment]
> Hi Ashish, your error relates to DPDK (as opposed to UDPDK) so you may get more help by asking to the [DPDK](https://github.com/DPDK/dpdk) community. The documentation in your link refers to the latest version, that's why it may be inconsistent with the version you use; I recommend checking the [docs for 20.05](https://doc.dpdk.org/guides-20.05/).

Okay, thanks
